# Generated by Django 5.0.7 on 2024-08-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TsmyIntranetusuario',
            fields=[
                ('usuarioid', models.SmallAutoField(primary_key=True, serialize=False)),
                ('usuariodescricao', models.CharField(max_length=255)),
                ('nroempresa', models.IntegerField()),
                ('login', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tsmy_intranetusuario',
                'managed': False,
            },
        ),
    ]
