# Generated by Django 5.0.7 on 2024-09-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmyUsuario',
            fields=[
                ('idusu', models.FloatField(db_comment='ADICIONA ID POR SMY_USUARIO_SEQ', primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('dtaatualizacao', models.DateField(blank=True, null=True)),
                ('dtabloqueio', models.DateField(blank=True, null=True)),
                ('login', models.CharField(blank=True, max_length=100, null=True)),
                ('senha', models.CharField(blank=True, max_length=100, null=True)),
                ('nroempresa', models.FloatField(blank=True, null=True)),
                ('ramal', models.FloatField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'smy_usuario',
                'managed': False,
            },
        ),
    ]
