# Generated by Django 5.0.7 on 2024-09-25 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0002_smyusuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smyusuario',
            options={},
        ),
    ]
