# Generated by Django 5.0.7 on 2024-08-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "controle_uni",
            "0002_rename_idobservacao_tsmyeuobservacaoficha_id_observacao",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="tsmyeufichacolab",
            name="sit_ficha",
            field=models.CharField(
                blank=True,
                choices=[("A", "Ativo"), ("C", "Cancelada"), ("D", "Desativada")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tsmyeufichacolab",
            name="sit_produto",
            field=models.CharField(
                blank=True,
                choices=[
                    ("C", "Cadastrada"),
                    ("TE", "Troca Envio"),
                    ("TR", "Troca Recebimento"),
                    ("TRA", "Troca Recebimento Antiga"),
                    ("D", "Devolução"),
                    ("DA", "Devolução Antiga"),
                    ("DC", "Devolução Cargo"),
                    ("DM", "Demissão"),
                    ("OR", "Ordem de Requisição"),
                ],
                max_length=3,
                null=True,
            ),
        ),
    ]
