# Generated by Django 5.0.7 on 2024-09-25 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_uni', '0003_alter_tsmyeufichacolab_sit_ficha_and_more'),
        ('intranet', '0003_alter_smyusuario_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tsmyeucolaboradores',
            name='data_alteracao',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='tsmyeucolaboradores',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tsmyeucolaboradores',
            name='usuario_alteracao',
            field=models.ForeignKey(db_column='id_usuario_alteracao', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_usuario_alteracao', to='intranet.smyusuario'),
        ),
        migrations.AddField(
            model_name='tsmyeucolaboradores',
            name='usuario_criacao',
            field=models.ForeignKey(db_column='id_usuario_criacao', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_usuario_criacao', to='intranet.smyusuario'),
        ),
    ]
