# Generated by Django 5.0.7 on 2024-09-25 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_uni', '0004_tsmyeucolaboradores_data_alteracao_and_more'),
        ('intranet', '0003_alter_smyusuario_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tsmyeuarquivo',
            name='data_alteracao',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='tsmyeuarquivo',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tsmyeuarquivo',
            name='usuario_alteracao',
            field=models.ForeignKey(db_column='id_usuario_alteracao', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_usuario_alteracao', to='intranet.smyusuario'),
        ),
        migrations.AddField(
            model_name='tsmyeuarquivo',
            name='usuario_criacao',
            field=models.ForeignKey(db_column='id_usuario_criacao', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_usuario_criacao', to='intranet.smyusuario'),
        ),
        migrations.AddField(
            model_name='tsmyeuautorizacao',
            name='data_alteracao',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='tsmyeuautorizacao',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tsmyeuautorizacao',
            name='usuario_alteracao',
            field=models.ForeignKey(db_column='id_usuario_alteracao', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_usuario_alteracao', to='intranet.smyusuario'),
        ),
        migrations.AddField(
            model_name='tsmyeuautorizacao',
            name='usuario_criacao',
            field=models.ForeignKey(db_column='id_usuario_criacao', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_usuario_criacao', to='intranet.smyusuario'),
        ),
        migrations.AddField(
            model_name='tsmyeuca',
            name='data_alteracao',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='tsmyeuca',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tsmyeuca',
            name='usuario_alteracao',
            field=models.ForeignKey(db_column='id_usuario_alteracao', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_usuario_alteracao', to='intranet.smyusuario'),
        ),
        migrations.AddField(
            model_name='tsmyeuca',
            name='usuario_criacao',
            field=models.ForeignKey(db_column='id_usuario_criacao', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_usuario_criacao', to='intranet.smyusuario'),
        ),
        migrations.AddField(
            model_name='tsmyeucargoagrup',
            name='data_alteracao',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='tsmyeucargoagrup',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tsmyeucargoagrup',
            name='usuario_alteracao',
            field=models.ForeignKey(db_column='id_usuario_alteracao', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_usuario_alteracao', to='intranet.smyusuario'),
        ),
        migrations.AddField(
            model_name='tsmyeucargoagrup',
            name='usuario_criacao',
            field=models.ForeignKey(db_column='id_usuario_criacao', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_usuario_criacao', to='intranet.smyusuario'),
        ),
        migrations.AddField(
            model_name='tsmyeucargoepiunif',
            name='data_alteracao',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='tsmyeucargoepiunif',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tsmyeucargoepiunif',
            name='usuario_alteracao',
            field=models.ForeignKey(db_column='id_usuario_alteracao', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_usuario_alteracao', to='intranet.smyusuario'),
        ),
        migrations.AddField(
            model_name='tsmyeucargoepiunif',
            name='usuario_criacao',
            field=models.ForeignKey(db_column='id_usuario_criacao', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_usuario_criacao', to='intranet.smyusuario'),
        ),
        migrations.AddField(
            model_name='tsmyeucargos',
            name='data_alteracao',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='tsmyeucargos',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tsmyeucargos',
            name='usuario_alteracao',
            field=models.ForeignKey(db_column='id_usuario_alteracao', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_usuario_alteracao', to='intranet.smyusuario'),
        ),
        migrations.AddField(
            model_name='tsmyeucargos',
            name='usuario_criacao',
            field=models.ForeignKey(db_column='id_usuario_criacao', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_usuario_criacao', to='intranet.smyusuario'),
        ),
        migrations.AddField(
            model_name='tsmyeucodloginform',
            name='data_alteracao',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='tsmyeucodloginform',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tsmyeucodloginform',
            name='usuario_alteracao',
            field=models.ForeignKey(db_column='id_usuario_alteracao', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_usuario_alteracao', to='intranet.smyusuario'),
        ),
        migrations.AddField(
            model_name='tsmyeucodloginform',
            name='usuario_criacao',
            field=models.ForeignKey(db_column='id_usuario_criacao', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_usuario_criacao', to='intranet.smyusuario'),
        ),
        migrations.AddField(
            model_name='tsmyeufichacolab',
            name='data_alteracao',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='tsmyeufichacolab',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tsmyeufichacolab',
            name='usuario_alteracao',
            field=models.ForeignKey(db_column='id_usuario_alteracao', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_usuario_alteracao', to='intranet.smyusuario'),
        ),
        migrations.AddField(
            model_name='tsmyeufichacolab',
            name='usuario_criacao',
            field=models.ForeignKey(db_column='id_usuario_criacao', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_usuario_criacao', to='intranet.smyusuario'),
        ),
        migrations.AddField(
            model_name='tsmyeulancto',
            name='data_alteracao',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='tsmyeulancto',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tsmyeulancto',
            name='usuario_alteracao',
            field=models.ForeignKey(db_column='id_usuario_alteracao', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_usuario_alteracao', to='intranet.smyusuario'),
        ),
        migrations.AddField(
            model_name='tsmyeulancto',
            name='usuario_criacao',
            field=models.ForeignKey(db_column='id_usuario_criacao', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_usuario_criacao', to='intranet.smyusuario'),
        ),
        migrations.AddField(
            model_name='tsmyeulog',
            name='data_alteracao',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='tsmyeulog',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tsmyeulog',
            name='usuario_alteracao',
            field=models.ForeignKey(db_column='id_usuario_alteracao', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_usuario_alteracao', to='intranet.smyusuario'),
        ),
        migrations.AddField(
            model_name='tsmyeulog',
            name='usuario_criacao',
            field=models.ForeignKey(db_column='id_usuario_criacao', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_usuario_criacao', to='intranet.smyusuario'),
        ),
        migrations.AddField(
            model_name='tsmyeumovimentnf',
            name='data_alteracao',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='tsmyeumovimentnf',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tsmyeumovimentnf',
            name='usuario_alteracao',
            field=models.ForeignKey(db_column='id_usuario_alteracao', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_usuario_alteracao', to='intranet.smyusuario'),
        ),
        migrations.AddField(
            model_name='tsmyeumovimentnf',
            name='usuario_criacao',
            field=models.ForeignKey(db_column='id_usuario_criacao', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_usuario_criacao', to='intranet.smyusuario'),
        ),
        migrations.AddField(
            model_name='tsmyeuobservacaoficha',
            name='data_alteracao',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='tsmyeuobservacaoficha',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tsmyeuobservacaoficha',
            name='usuario_alteracao',
            field=models.ForeignKey(db_column='id_usuario_alteracao', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_usuario_alteracao', to='intranet.smyusuario'),
        ),
        migrations.AddField(
            model_name='tsmyeuobservacaoficha',
            name='usuario_criacao',
            field=models.ForeignKey(db_column='id_usuario_criacao', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_usuario_criacao', to='intranet.smyusuario'),
        ),
        migrations.AddField(
            model_name='tsmyeuparametro',
            name='data_alteracao',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='tsmyeuparametro',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tsmyeuparametro',
            name='usuario_alteracao',
            field=models.ForeignKey(db_column='id_usuario_alteracao', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_usuario_alteracao', to='intranet.smyusuario'),
        ),
        migrations.AddField(
            model_name='tsmyeuparametro',
            name='usuario_criacao',
            field=models.ForeignKey(db_column='id_usuario_criacao', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_usuario_criacao', to='intranet.smyusuario'),
        ),
    ]
