# Generated by Django 5.0.7 on 2024-09-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_uni', '0005_tsmyeuarquivo_data_alteracao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tsmyeucolaboradores',
            name='candidato',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
