# Generated by Django 5.0.7 on 2024-09-27 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_uni', '0006_tsmyeucolaboradores_candidato'),
        ('intranet', '0003_alter_smyusuario_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TsmyEuFuncao',
            fields=[
                ('data_criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('data_alteracao', models.DateTimeField(auto_now=True, null=True)),
                ('cod_funcao', models.SmallAutoField(primary_key=True, serialize=False)),
                ('nome_funcao', models.CharField(blank=True, max_length=50, null=True)),
                ('usuario_alteracao', models.ForeignKey(db_column='id_usuario_alteracao', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_usuario_alteracao', to='intranet.smyusuario')),
                ('usuario_criacao', models.ForeignKey(db_column='id_usuario_criacao', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_usuario_criacao', to='intranet.smyusuario')),
            ],
            options={
                'db_table': 'tsmy_eu_funcao',
            },
        ),
        migrations.CreateModel(
            name='TsmyEuSetor',
            fields=[
                ('data_criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('data_alteracao', models.DateTimeField(auto_now=True, null=True)),
                ('cod_setor', models.SmallAutoField(primary_key=True, serialize=False)),
                ('nome_setor', models.CharField(blank=True, max_length=50, null=True)),
                ('usuario_alteracao', models.ForeignKey(db_column='id_usuario_alteracao', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_usuario_alteracao', to='intranet.smyusuario')),
                ('usuario_criacao', models.ForeignKey(db_column='id_usuario_criacao', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_usuario_criacao', to='intranet.smyusuario')),
            ],
            options={
                'db_table': 'tsmy_eu_setor',
            },
        ),
    ]
