# Generated by Django 5.0.7 on 2024-10-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_uni', '0008_alter_tsmyeusetor_cod_setor'),
    ]

    operations = [
        migrations.AddField(
            model_name='tsmyeucolaboradores',
            name='candidato',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
