# Generated by Django 5.0.7 on 2024-08-01 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapFamilia',
            fields=[
                ('seqfamilia', models.BigIntegerField(primary_key=True, serialize=False)),
                ('familia', models.CharField(max_length=35)),
            ],
            options={
                'db_table': 'map_familia',
            },
        ),
        migrations.CreateModel(
            name='MaxCodgeraloper',
            fields=[
                ('codgeraloper', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'max_codgeraloper',
            },
        ),
        migrations.CreateModel(
            name='MapProduto',
            fields=[
                ('seqproduto', models.BigIntegerField(primary_key=True, serialize=False)),
                ('desccompleta', models.CharField(max_length=250)),
                ('descreduzida', models.CharField(max_length=250)),
                ('seqfamilia', models.ForeignKey(db_column='seqfamilia', on_delete=django.db.models.deletion.DO_NOTHING, to='c5.mapfamilia')),
            ],
            options={
                'db_table': 'map_produto',
            },
        ),
        migrations.CreateModel(
            name='MapFamatributo',
            fields=[
                ('seqfamilia', models.OneToOneField(db_column='seqfamilia', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='c5.mapfamilia')),
                ('descatributo', models.CharField(max_length=100)),
                ('valor', models.CharField(blank=True, max_length=15, null=True)),
                ('usuarioalteracao', models.CharField(blank=True, max_length=12, null=True)),
            ],
            options={
                'db_table': 'map_famatributo',
                'unique_together': {('seqfamilia', 'descatributo')},
            },
        ),
        migrations.CreateModel(
            name='MapProdcodigo',
            fields=[
                ('codacesso', models.TextField(primary_key=True, serialize=False)),
                ('tipcodigo', models.TextField()),
                ('seqproduto', models.ForeignKey(blank=True, db_column='seqproduto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='c5.mapproduto')),
            ],
            options={
                'db_table': 'map_prodcodigo',
                'unique_together': {('codacesso',)},
            },
        ),
    ]
