# Generated by Django 5.0.7 on 2024-08-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c5', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeEmpresa',
            fields=[
                ('nroempresa', models.IntegerField(primary_key=True, serialize=False)),
                ('fantasia', models.CharField(max_length=30)),
                ('razaosocial', models.CharField(max_length=60)),
                ('nomereduzido', models.CharField(max_length=15, unique=True)),
            ],
            options={
                'db_table': 'ge_empresa',
                'managed': False,
            },
        ),
    ]
