# Generated by Django 5.0.7 on 2024-09-27 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('controle_uni', '0007_tsmyeufuncao_tsmyeusetor'),
        ('intranet', '0003_alter_smyusuario_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetrabArquivoImportacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('data_alteracao', models.DateTimeField(auto_now=True, null=True)),
                ('nome_arquivo', models.CharField(max_length=100)),
                ('mes', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('resposta_servidor', models.CharField(max_length=100)),
                ('usuario_alteracao', models.ForeignKey(db_column='id_usuario_alteracao', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_usuario_alteracao', to='intranet.smyusuario')),
                ('usuario_criacao', models.ForeignKey(db_column='id_usuario_criacao', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_usuario_criacao', to='intranet.smyusuario')),
            ],
            options={
                'db_table': 'setrab_arquivo_importacao',
            },
        ),
        migrations.CreateModel(
            name='SetrabCargoRel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('data_alteracao', models.DateTimeField(auto_now=True, null=True)),
                ('id_cargo_setrab', models.IntegerField()),
                ('id_cargo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='controle_uni.tsmyeucargos')),
                ('usuario_alteracao', models.ForeignKey(db_column='id_usuario_alteracao', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_usuario_alteracao', to='intranet.smyusuario')),
                ('usuario_criacao', models.ForeignKey(db_column='id_usuario_criacao', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_usuario_criacao', to='intranet.smyusuario')),
            ],
            options={
                'db_table': 'setrab_cargo_rel',
            },
        ),
        migrations.CreateModel(
            name='SetrabColaboradorRel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('data_alteracao', models.DateTimeField(auto_now=True, null=True)),
                ('id_colaborador_setrab', models.IntegerField()),
                ('id_colaborador', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='controle_uni.tsmyeucolaboradores')),
                ('usuario_alteracao', models.ForeignKey(db_column='id_usuario_alteracao', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_usuario_alteracao', to='intranet.smyusuario')),
                ('usuario_criacao', models.ForeignKey(db_column='id_usuario_criacao', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_usuario_criacao', to='intranet.smyusuario')),
            ],
            options={
                'db_table': 'setrab_colaborador_rel',
            },
        ),
        migrations.CreateModel(
            name='SetrabEmpresaRel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('data_alteracao', models.DateTimeField(auto_now=True, null=True)),
                ('id_empresa', models.IntegerField()),
                ('id_empresa_setrab', models.IntegerField()),
                ('usuario_alteracao', models.ForeignKey(db_column='id_usuario_alteracao', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_usuario_alteracao', to='intranet.smyusuario')),
                ('usuario_criacao', models.ForeignKey(db_column='id_usuario_criacao', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_usuario_criacao', to='intranet.smyusuario')),
            ],
            options={
                'db_table': 'setrab_empresa_rel',
            },
        ),
        migrations.CreateModel(
            name='SetrabFuncaoRel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('data_alteracao', models.DateTimeField(auto_now=True, null=True)),
                ('id_funcao_setrab', models.IntegerField()),
                ('id_funcao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='controle_uni.tsmyeufuncao')),
                ('usuario_alteracao', models.ForeignKey(db_column='id_usuario_alteracao', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_usuario_alteracao', to='intranet.smyusuario')),
                ('usuario_criacao', models.ForeignKey(db_column='id_usuario_criacao', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_usuario_criacao', to='intranet.smyusuario')),
            ],
            options={
                'db_table': 'setrab_funcao_rel',
            },
        ),
        migrations.CreateModel(
            name='SetrabSetorRel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('data_alteracao', models.DateTimeField(auto_now=True, null=True)),
                ('id_setor_setrab', models.IntegerField()),
                ('id_setor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='controle_uni.tsmyeusetor')),
                ('usuario_alteracao', models.ForeignKey(db_column='id_usuario_alteracao', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_usuario_alteracao', to='intranet.smyusuario')),
                ('usuario_criacao', models.ForeignKey(db_column='id_usuario_criacao', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_usuario_criacao', to='intranet.smyusuario')),
            ],
            options={
                'db_table': 'setrab_setor_rel',
            },
        ),
    ]
