# Generated by Django 5.0.7 on 2024-09-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setrab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setrabcolaboradorrel',
            name='nro_empresa',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
