# Generated by Django 5.0.7 on 2024-09-30 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setrab', '0002_setrabcolaboradorrel_nro_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='setrabsetorrel',
            name='nro_empresa',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SetrabColaboradorRel',
        ),
    ]
