# Generated by Django 5.0.7 on 2024-10-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setrab', '0003_setrabsetorrel_nro_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setrabcargorel',
            name='nro_empresa',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='setrabfuncaorel',
            name='nro_empresa',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='setrabsetorrel',
            name='nro_empresa',
            field=models.IntegerField(null=True),
        ),
    ]
