# Generated by Django 5.0.7 on 2024-10-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setrab', '0004_setrabcargorel_nro_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setrabarquivoimportacao',
            name='arquivo_erro',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
