# Generated by Django 5.0.7 on 2024-08-01 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("c5", "0001_initial"),
        ("intranet", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TsmyEuCodLogInform",
            fields=[
                ("cod_inform", models.AutoField(primary_key=True, serialize=False)),
                ("informacao", models.CharField(max_length=200)),
            ],
            options={
                "db_table": "tsmy_eu_cod_log_inform",
            },
        ),
        migrations.CreateModel(
            name="TsmyEuParametro",
            fields=[
                (
                    "id_parametro",
                    models.SmallAutoField(primary_key=True, serialize=False),
                ),
                (
                    "nome_parametro",
                    models.CharField(blank=True, max_length=25, null=True),
                ),
                ("status", models.CharField(blank=True, max_length=1, null=True)),
                ("parametro", models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                "db_table": "tsmy_eu_parametro",
            },
        ),
        migrations.CreateModel(
            name="TsmyEuCa",
            fields=[
                (
                    "ca",
                    models.CharField(max_length=5, primary_key=True, serialize=False),
                ),
                ("dt_validade", models.DateTimeField(blank=True, null=True)),
                ("dt_inclusao", models.DateTimeField(auto_now_add=True, null=True)),
                ("dt_alteracao", models.DateTimeField(auto_now=True, null=True)),
                (
                    "usuarioalt",
                    models.ForeignKey(
                        blank=True,
                        db_column="usuarioalt",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="fk_ca_alteracao_lancto",
                        to="intranet.tsmyintranetusuario",
                    ),
                ),
                (
                    "usuarioincl",
                    models.ForeignKey(
                        blank=True,
                        db_column="usuarioincl",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="fk_ca_inclusao_lancto",
                        to="intranet.tsmyintranetusuario",
                    ),
                ),
            ],
            options={
                "db_table": "tsmy_eu_ca",
            },
        ),
        migrations.CreateModel(
            name="TsmyEuCargoAgrup",
            fields=[
                (
                    "codigo",
                    models.SmallAutoField(
                        db_column="valor", primary_key=True, serialize=False
                    ),
                ),
                ("descricao", models.CharField(max_length=50)),
                ("dt_inclusao", models.DateTimeField(blank=True, null=True)),
                ("dt_alteracao", models.DateTimeField(blank=True, null=True)),
                (
                    "usuarioalt",
                    models.ForeignKey(
                        blank=True,
                        db_column="usuarioalt",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fk_usuario_alteracao_cargo_agrup",
                        to="intranet.tsmyintranetusuario",
                    ),
                ),
                (
                    "usuarioincl",
                    models.ForeignKey(
                        blank=True,
                        db_column="usuarioincl",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fk_usuario_inclusao_cargo_agrup",
                        to="intranet.tsmyintranetusuario",
                    ),
                ),
            ],
            options={
                "db_table": "tsmy_eu_cargo_agrup",
            },
        ),
        migrations.CreateModel(
            name="TsmyEuCargos",
            fields=[
                (
                    "cod_funcao",
                    models.SmallAutoField(primary_key=True, serialize=False),
                ),
                ("funcao", models.CharField(blank=True, max_length=50, null=True)),
                ("dt_inclusao", models.DateTimeField(blank=True, null=True)),
                ("dt_alteracao", models.DateTimeField(blank=True, null=True)),
                (
                    "usuarioalt",
                    models.ForeignKey(
                        blank=True,
                        db_column="usuarioalt",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fk_usuario_alteracao_cargo",
                        to="intranet.tsmyintranetusuario",
                    ),
                ),
                (
                    "usuarioincl",
                    models.ForeignKey(
                        blank=True,
                        db_column="usuarioincl",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fk_usuario_inclusao_cargo",
                        to="intranet.tsmyintranetusuario",
                    ),
                ),
            ],
            options={
                "db_table": "tsmy_eu_cargos",
            },
        ),
        migrations.CreateModel(
            name="TsmyEuCargoEpiUnif",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seqfamilia", models.IntegerField(blank=True, null=True)),
                ("quantidade", models.IntegerField(blank=True, null=True)),
                ("dt_inclusao", models.DateTimeField(blank=True, null=True)),
                ("dt_alteracao", models.DateTimeField(blank=True, null=True)),
                (
                    "usuarioalt",
                    models.ForeignKey(
                        blank=True,
                        db_column="usuarioalt",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fk_usuario_alteracao_epi_unif",
                        to="intranet.tsmyintranetusuario",
                    ),
                ),
                (
                    "usuarioincl",
                    models.ForeignKey(
                        blank=True,
                        db_column="usuarioincl",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fk_usuario_inclusao_epi_unif",
                        to="intranet.tsmyintranetusuario",
                    ),
                ),
                (
                    "valor",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_valor",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fk_codigo_epi_unif",
                        to="controleUni.tsmyeucargoagrup",
                    ),
                ),
                (
                    "cod_funcao",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_cod_funcao",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fk_cargo_epi_unif",
                        to="controleUni.tsmyeucargos",
                    ),
                ),
            ],
            options={
                "db_table": "tsmy_eu_cargo_epi_unif",
            },
        ),
        migrations.CreateModel(
            name="TsmyEuAutorizacao",
            fields=[
                (
                    "id_autorizacao",
                    models.SmallAutoField(primary_key=True, serialize=False),
                ),
                ("dt_inclusao", models.DateTimeField()),
                ("matricula", models.IntegerField()),
                (
                    "usuarioincl",
                    models.ForeignKey(
                        blank=True,
                        db_column="usuarioincl",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fk_usuario_inclusao_autorizacao",
                        to="intranet.tsmyintranetusuario",
                    ),
                ),
                (
                    "cod_funcao",
                    models.ForeignKey(
                        blank=True,
                        db_column="cod_funcao",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fk_cargo_autorizacao",
                        to="controleUni.tsmyeucargos",
                    ),
                ),
            ],
            options={
                "db_table": "tsmy_eu_autorizacao",
            },
        ),
        migrations.CreateModel(
            name="TsmyEuColaboradores",
            fields=[
                ("id_colab", models.SmallAutoField(primary_key=True, serialize=False)),
                ("nroempresa", models.IntegerField(blank=True, null=True)),
                ("matricula", models.IntegerField(blank=True, null=True, unique=True)),
                ("cpf", models.IntegerField(blank=True, null=True, unique=True)),
                ("nome", models.CharField(blank=True, max_length=60, null=True)),
                ("genero", models.CharField(blank=True, max_length=1, null=True)),
                (
                    "dt_adm",
                    models.DateField(blank=True, db_column="dt_admissao", null=True),
                ),
                ("dt_desligamento", models.DateField(blank=True, null=True)),
                ("dt_inclusao", models.DateTimeField(auto_now_add=True, null=True)),
                ("dt_alteracao", models.DateTimeField(auto_now=True, null=True)),
                ("dt_experiencia", models.DateTimeField(blank=True, null=True)),
                (
                    "cod_funcao",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_cod_funcao",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="fk_cargo_colab",
                        to="controleUni.tsmyeucargos",
                    ),
                ),
                (
                    "cod_funcao_ant",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_cod_funcao_ant",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fk_cargo_ant_colab",
                        to="controleUni.tsmyeucargos",
                    ),
                ),
                (
                    "cod_funcao_nova",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_cod_funcao_nova",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fk_cargo_nova_colab",
                        to="controleUni.tsmyeucargos",
                    ),
                ),
                (
                    "usuarioalt",
                    models.ForeignKey(
                        blank=True,
                        db_column="usuarioalt",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fk_usuario_alteracao_colab",
                        to="intranet.tsmyintranetusuario",
                    ),
                ),
                (
                    "usuarioincl",
                    models.ForeignKey(
                        blank=True,
                        db_column="usuarioincl",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fk_usuario_inclusao_colab",
                        to="intranet.tsmyintranetusuario",
                    ),
                ),
            ],
            options={
                "db_table": "tsmy_eu_colaboradores",
            },
        ),
        migrations.CreateModel(
            name="TsmyEuArquivo",
            fields=[
                ("id_aquivo", models.AutoField(primary_key=True, serialize=False)),
                ("nome_arquivo", models.CharField(max_length=100)),
                (
                    "arquivo_assinado",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "tipo_arquivo",
                    models.CharField(
                        blank=True,
                        db_comment="Tipo de arquivo: RU(Recibo Uniforme), RE(Recibo EPI), RR(Recibo Rescisão) ",
                        max_length=6,
                        null=True,
                    ),
                ),
                ("dt_inclusao", models.DateTimeField(auto_now_add=True, null=True)),
                ("dt_alteracao", models.DateTimeField(auto_now=True, null=True)),
                (
                    "usuarioalt",
                    models.ForeignKey(
                        blank=True,
                        db_column="usuarioalt",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fk_arquivo_alteracao_lancto",
                        to="intranet.tsmyintranetusuario",
                    ),
                ),
                (
                    "usuarioincl",
                    models.ForeignKey(
                        blank=True,
                        db_column="usuarioincl",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fk_arquivo_inclusao_lancto",
                        to="intranet.tsmyintranetusuario",
                    ),
                ),
                (
                    "matricula",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_colab_matricula",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fk_matricula_arquivo",
                        to="controleUni.tsmyeucolaboradores",
                    ),
                ),
            ],
            options={
                "db_table": "tsmy_eu_arquivo",
            },
        ),
        migrations.CreateModel(
            name="TsmyEuFichaColab",
            fields=[
                ("nroempresa", models.IntegerField(blank=True, null=True)),
                ("quantidade", models.IntegerField(blank=True, null=True)),
                ("dt_inclusao", models.DateTimeField(auto_now_add=True, null=True)),
                ("dt_alteracao", models.DateTimeField(auto_now=True, null=True)),
                (
                    "sit_produto",
                    models.CharField(
                        blank=True,
                        db_comment="Tipos da Ficha: C(Cadastrada), T(Troca), A(Aguardando Aprovação de Troca), TA(Troca Antiga), D(Devolução), DC(Devolução de Cargo), DA(Devolução Antiga)",
                        max_length=2,
                        null=True,
                    ),
                ),
                ("sit_ficha", models.CharField(blank=True, max_length=1, null=True)),
                ("id_troca", models.IntegerField(blank=True, null=True)),
                ("id_ficha", models.AutoField(primary_key=True, serialize=False)),
                ("custoAtual", models.CharField(blank=True, max_length=50, null=True)),
                ("dataCusto", models.DateField(blank=True, null=True)),
                ("percentual", models.CharField(blank=True, max_length=50, null=True)),
                ("nro_ca", models.CharField(blank=True, max_length=5, null=True)),
                ("dt_validade", models.DateTimeField(blank=True, null=True)),
                (
                    "cod_funcao",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_cod_funcao",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fk_cargo_ficha_colab",
                        to="controleUni.tsmyeucargos",
                    ),
                ),
                (
                    "cpf",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_colab_cpf",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fk_cpf_ficha_colab",
                        to="controleUni.tsmyeucolaboradores",
                    ),
                ),
                (
                    "matricula",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_colab_matricula",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fk_matricula_ficha_colab",
                        to="controleUni.tsmyeucolaboradores",
                    ),
                ),
                (
                    "reciboEpi",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_reciboEpi",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fk_recibo_epi_ficha_colab",
                        to="controleUni.tsmyeuarquivo",
                    ),
                ),
                (
                    "reciboPerda",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_reciboPerda",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fk_recibo_perda_ficha_colab",
                        to="controleUni.tsmyeuarquivo",
                    ),
                ),
                (
                    "reciboRescisao",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_reciboRecisao",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fk_recibo_recisao_ficha_colab",
                        to="controleUni.tsmyeuarquivo",
                    ),
                ),
                (
                    "reciboUni",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_reciboUni",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fk_recibo_uni_ficha_colab",
                        to="controleUni.tsmyeuarquivo",
                    ),
                ),
                (
                    "seqproduto",
                    models.ForeignKey(
                        blank=True,
                        db_column="seqproduto",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="fk_seqproduto_ficha_colab",
                        to="c5.mapproduto",
                    ),
                ),
                (
                    "usuarioalt",
                    models.ForeignKey(
                        blank=True,
                        db_column="usuarioalt",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fk_usuario_alteracao_ficha_colab",
                        to="intranet.tsmyintranetusuario",
                    ),
                ),
                (
                    "usuarioincl",
                    models.ForeignKey(
                        blank=True,
                        db_column="usuarioincl",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fk_usuario_inclusao_ficha_colab",
                        to="intranet.tsmyintranetusuario",
                    ),
                ),
            ],
            options={
                "db_table": "tsmy_eu_ficha_colab",
            },
        ),
        migrations.AddField(
            model_name="tsmyeuarquivo",
            name="id_ficha",
            field=models.ForeignKey(
                blank=True,
                db_column="id_ficha",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fk_id_ficha_arquivo",
                to="controleUni.tsmyeufichacolab",
            ),
        ),
        migrations.CreateModel(
            name="TsmyEuLancto",
            fields=[
                ("id_lancto", models.AutoField(primary_key=True, serialize=False)),
                ("nroemporig", models.IntegerField(blank=True, null=True)),
                ("nroempdest", models.IntegerField(blank=True, null=True)),
                ("dt_arquivo", models.DateField(blank=True, null=True)),
                ("quantidade", models.IntegerField(blank=True, null=True)),
                ("tipo", models.CharField(blank=True, max_length=1, null=True)),
                ("dt_inclusao", models.DateTimeField(auto_now_add=True, null=True)),
                ("dt_alteracao", models.DateTimeField(auto_now=True, null=True)),
                (
                    "cgo",
                    models.ForeignKey(
                        blank=True,
                        db_column="cgo",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fk_cgo_lancto",
                        to="c5.maxcodgeraloper",
                    ),
                ),
                (
                    "id_ficha",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_ficha",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fk_id_ficha_lancto",
                        to="controleUni.tsmyeufichacolab",
                    ),
                ),
                (
                    "matricula",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_colab_matricula",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fk_matricula_lancto",
                        to="controleUni.tsmyeucolaboradores",
                    ),
                ),
                (
                    "seqproduto",
                    models.ForeignKey(
                        blank=True,
                        db_column="seqproduto",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="fk_seqproduto_lancto",
                        to="c5.mapproduto",
                    ),
                ),
                (
                    "usuarioalt",
                    models.ForeignKey(
                        blank=True,
                        db_column="usuarioalt",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fk_usuario_alteracao_lancto",
                        to="intranet.tsmyintranetusuario",
                    ),
                ),
                (
                    "usuarioincl",
                    models.ForeignKey(
                        blank=True,
                        db_column="usuarioincl",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fk_usuario_inclusao_lancto",
                        to="intranet.tsmyintranetusuario",
                    ),
                ),
            ],
            options={
                "db_table": "tsmy_eu_lancto",
            },
        ),
        migrations.CreateModel(
            name="TsmyEuLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tabela", models.CharField(max_length=50)),
                ("acao", models.CharField(max_length=20)),
                ("campo", models.CharField(max_length=50)),
                ("antes", models.CharField(max_length=50)),
                ("depois", models.CharField(max_length=50)),
                ("dt_inclusao", models.DateTimeField()),
                (
                    "cod_inform",
                    models.ForeignKey(
                        blank=True,
                        db_column="cod_inform",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fk_cod_inform_log",
                        to="controleUni.tsmyeucodloginform",
                    ),
                ),
                (
                    "usuarioincl",
                    models.ForeignKey(
                        blank=True,
                        db_column="usuarioincl",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fk_usuario_inclusao_log",
                        to="intranet.tsmyintranetusuario",
                    ),
                ),
            ],
            options={
                "db_table": "tsmy_eu_log",
            },
        ),
        migrations.CreateModel(
            name="TsmyEuMovimentNf",
            fields=[
                ("id_mov_nf", models.AutoField(primary_key=True, serialize=False)),
                ("nroempresa_orig", models.IntegerField(blank=True, null=True)),
                ("nroempresa_dest", models.IntegerField(blank=True, null=True)),
                ("quantidade", models.IntegerField(blank=True, null=True)),
                ("dt_inclusao", models.DateTimeField(blank=True, null=True)),
                ("matricula", models.IntegerField(blank=True, null=True)),
                ("notafiscal", models.IntegerField(blank=True, null=True)),
                ("tipo", models.CharField(blank=True, max_length=1, null=True)),
                ("interno", models.IntegerField(blank=True, null=True)),
                (
                    "cgo",
                    models.ForeignKey(
                        blank=True,
                        db_column="cgo",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fk_cgo_mov_nf",
                        to="c5.maxcodgeraloper",
                    ),
                ),
                (
                    "seqproduto",
                    models.ForeignKey(
                        blank=True,
                        db_column="seqproduto",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="fk_seqproduto_mov_nf",
                        to="c5.mapproduto",
                    ),
                ),
                (
                    "usuarioincl",
                    models.ForeignKey(
                        blank=True,
                        db_column="usuarioincl",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fk_usuario_inclusao_mov_nf",
                        to="intranet.tsmyintranetusuario",
                    ),
                ),
            ],
            options={
                "db_table": "tsmy_eu_moviment_nf",
            },
        ),
        migrations.CreateModel(
            name="TsmyEuObservacaoFicha",
            fields=[
                ("id_observacao", models.AutoField(primary_key=True, serialize=False)),
                ("observacao", models.CharField(max_length=200)),
                (
                    "tipo",
                    models.CharField(
                        blank=True,
                        choices=[("P", "Perda"), ("T", "Troca")],
                        max_length=4,
                        null=True,
                    ),
                ),
                ("dt_inclusao", models.DateTimeField(auto_now_add=True, null=True)),
                ("dt_alteracao", models.DateTimeField(auto_now=True, null=True)),
                (
                    "usuarioalt",
                    models.ForeignKey(
                        blank=True,
                        db_column="usuarioalt",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fk_observacao_alteracao_lancto",
                        to="intranet.tsmyintranetusuario",
                    ),
                ),
                (
                    "usuarioincl",
                    models.ForeignKey(
                        blank=True,
                        db_column="usuarioincl",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fk_observacao_inclusao_lancto",
                        to="intranet.tsmyintranetusuario",
                    ),
                ),
            ],
            options={
                "db_table": "tsmy_eu_observacao_ficha",
            },
        ),
        migrations.AddField(
            model_name="tsmyeufichacolab",
            name="id_observacao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="controleUni.tsmyeuobservacaoficha",
            ),
        ),
    ]
