# Generated by Django 5.0.7 on 2024-08-15 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controleUni', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tsmyeuobservacaoficha',
            old_name='idObservacao',
            new_name='id_observacao',
        ),
    ]
